---
output:
  pdf_document: 
    fig_caption: yes
    keep_tex: yes
  word_document:
    fig_height: 6
    fig_width: 8
---

```{r, echo=F, message=F, warning=F, cache=F, results=F}
require(knitr)
require(data.table)
require(ggplot2)
require(Hmisc)
require(reshape2)
require(plyr)
require(ggthemes)
require(texreg)
if (Sys.getenv("JAVA_HOME")!="")
  Sys.setenv(JAVA_HOME="")
options(java.parameters = "-Xmx8192m")
require(XLConnect)
require(RColorBrewer)
# set pander table-layout options
library(pander)
panderOptions('table.alignment.default', function(df)
    ifelse(sapply(df, is.numeric), 'right', 'left'))
panderOptions('table.split.table', Inf)
panderOptions('big.mark', ",")
panderOptions('keep.trailing.zeros', TRUE)

colorpalette = "Spectral"
fillpalette = "Spectral"

#colorpalette = "Set2"
#fillpalette = "Set2"
```


```{r, echo=F, message=F, warning=F, cache=T, results=F, comment = F, include = F, cache.rebuild = F}

##### prix des energies ####
prix_energie = fread("../AME_AMS_dataDGEC/parametrage modele/Prix_scenario_AME_BV_01_2017.csv", dec = ",")

prix_energie = melt(prix_energie,id.vars = "annee")

prix_energie[variable == "prix_elec", energie := "Electricité"]
prix_energie[variable == "prix_gaz", energie := "Gaz"]
prix_energie[variable == "prix_fioul", energie := "Fioul"]
prix_energie[variable == "prix_urbain", energie := "Urbain"]
prix_energie[variable == "prix_autres", energie := "Autres"]
prix_energie[variable == "CCE", energie := "CCE"]

prix_energie =dcast.data.table(prix_energie, annee~energie)
```

```{r, echo=F, message=FALSE, warning=F, cache=T, results=F, cache.rebuild = F}
source("analyse_param_utilisateurs.R",encoding = "ISO8859-1")

colors_syst= 
  data.table(SYSTEME_CHAUD =factor(unique(COD_SYSTEME_CHAUD$SYSTEME_CHAUD), 
                                   levels = c("Chaudière gaz","Chaudière condensation gaz",
                                                           "Tube radiant", "Tube radiant performant" ,
                                                           "Chaudière fioul","Chaudière condensation fioul",
                                                           "Electrique direct","Electrique direct performant",
                                                           "Cassette rayonnante","Cassette rayonnante performant",
                                                           "PAC","PAC performant",
                                                           "Rooftop", "Rooftop performant",
                                                            "DRV", "DRV performant",
                                                           "Autre système centralisé",  "Autre système centralisé performant",
                                                           "nr","NA"))
                         )

colors_syst = colors_syst[order(SYSTEME_CHAUD)]
colors_syst[,color := c("dodgerblue1","dodgerblue4", "blue1","blue4","springgreen1","springgreen4",
                "yellow1","yellow4","gold1","gold4","chocolate1","chocolate4","coral1","coral3",
                "salmon1","salmon4","red1","red4","gray86","gray86")]
```

```{r, echo=F, message=FALSE, warning=F, cache=T, results=F, cache.rebuild = F,include = F}
#### liste des fichiers à lire

wbfiles =  
"../tertiaire/model/Result_Excel/table_resultat_AME2016Briand.xls"

wbfiles[2] =
"../tertiaire_to_export/resultats_AME_run1/2050_allpol_CEE/table_resultat_2050_newcalib_allpol_CEE.xlsx"

wbfiles[3] =  
"../tertiaire/model/Result_Excel/parametrage_octobre/table_resultat_2030§_allpol_sansCEE.xlsx"

wbfiles[4] =  
"../tertiaire/model/Result_Excel/parametrage_octobre/table_resultat_2021_allpol_avecCEE.xlsx"

wbfiles[5] =  
"../tertiaire_to_export/resultats_AME_run2/2050_allpol_CEE_CC/table_resultat_2050_allpol_CEE_CC.xlsx"


#wbfiles[5] =  
#"../tertiaire_to_export/resultats_AME_run2/2050_allpol_CEE_CC/table_resultat_2050_allpol_CEE_CC.xlsx"

#### noms des scenarios ###
wbname = c("S1 : AME 2016",
           "S2 : AME 2017 run1",
           
           "S3 : AME 2017 run2 sans CEE",
           "S4 : AME 2017 run2 avec CEE",
           "S5 : AME 2017 run2 avec CEE et CC"
           #"S9 : AME 2017 run2 all pol CEE"
           
#           ,"S5 : AME 2017 all pol sans CEE bis", "S6 : AME 2017 all pol sans CEE ter"

#           "S2 : décret 60p", "S3 : décret 80p","S4 : décret 80p 400 euros"
#          ,"S4 : AMS2 CCE forte + elast" 
#         ,"S5 : AMS3 CCE tres forte"
)

#### choix du scenario de référence 
scenario_ref = c("S3 : AME 2017 run2 sans CEE")
scenario_toexport = c("S7 : AME 2017 run2 cal conso")
wbdir_scenario_toexport = c("../R/sorties_AME/")


scenarioshortnames = substring(wbname,1,2)
scenarios_taxeelec = ""

##### émissions de référence en MTCO2 
Em_ref_2012_tous_usages = 33.5
Em_ref_2012_chauffage = 23.6

Em_ref_1990_tous_usages = 28.8
Em_ref_1990_chauffage =  Em_ref_2012_chauffage/Em_ref_2012_tous_usages*Em_ref_1990_tous_usages 


##### lecture des resultats

source("read_resultats_csv.R")
##### Conso de référence en tWh 
Conso_ref_2012_chauffage = Conso[usage=="Chauffage" & annee == "2012" & scenario==scenario_ref, sum(value)/10^9]
Conso_ref_2012_tous_usages = Conso[ annee == "2012" & scenario==scenario_ref, sum(value)/10^9]

```


\clearpage
\newpage 

\clearpage
\pagebreak

\sextion{1) Evolution des consommmations }

## Ensemble du parc

```{r,echo=F, warning=F,include = F}
##### tableau des consos DGEC

Conso_nationale_usage = dcast.data.table(Conso, scenario + annee ~usage,fun.aggregate = function(x){sum(x)/10^9}, value.var = "value")

Conso_nationale_usage = melt(Conso_nationale_usage, id.vars = c("scenario","annee"), variable.name = "usage", value.name = "conso_tWhEF")


conso_parusage = dcast.data.table(Conso_nationale_usage[annee %in% c("2010","2013","2015","2020","2025","2030","2035","2050"),],
                                  scenario + annee ~ usage)

conso_parusage = conso_parusage[,list(Chauffage,
                                      AU_usages_ther = sum(ECS,Cuisson,Autre),
                                      Elec_spe = sum(Auxiliaires,Ventilation,Process,Bureautique,Eclairage,Froid_alimentaire),
                                      Climatisation,
 Total_RT=sum(Chauffage,Climatisation,ECS,Auxiliaires,Ventilation,Eclairage),                                      Total=sum(Chauffage,Climatisation,ECS,Cuisson,Autre,Auxiliaires,Ventilation,Process,Bureautique,Eclairage,Froid_alimentaire) ), by=c("scenario","annee")]

conso_parusage = melt(conso_parusage,id.vars = c("scenario","annee"),variable.name ="usage" )

conso_parusage[, conso_mtep := value/11630*10^3]
conso_parusage[, conso := value]


conso_parusage_tWh = dcast.data.table(conso_parusage, scenario + usage ~ annee, value.var = "value")
conso_parusage_tWh = conso_parusage_tWh[order(usage),]

conso_parusage_mtep = dcast.data.table(conso_parusage, scenario + usage ~ annee, value.var = "conso_mtep")
conso_parusage_mtep  = conso_parusage_mtep[order(usage),]

annee_ref = "2010"

evolconso = conso_parusage_tWh 

evolconso = evolconso[,list(scenario, usage,
                Evol_2015 = paste0(round((get("2015")/get(annee_ref)-1)*100, digits=1), " %"),
                Evol_2020 = paste0(round((get("2020")/get(annee_ref)-1)*100, digits=1), " %"),
                Evol_2020 = paste0(round((get("2025")/get(annee_ref)-1)*100, digits=1), " %"),
                Evol_2030 = paste0(round((get("2030")/get(annee_ref)-1)*100, digits=1), " %"),
                Evol_2035 = paste0(round((get("2035")/get(annee_ref)-1)*100, digits=1), " %"),
                Evol_2050 = paste0(round((get("2050")/get(annee_ref)-1)*100, digits=1), " %"))]


setnames(evolconso, c("scenario", "usage",paste(annee_ref,c(15,20,25,30,35,50), sep="-")))
#♦Consotab = merge(conso_parusage_mtep,evolconso,by=c("scenario","usage"))
###
##### Différence de conso totales par usage par rapport à un scénario de ref

comp_conso_ref = dcast.data.table(Conso_nationale_usage[annee %in% c(2010:2020,
                                                                     "2025","2030","2035","2040","2045","2050"),],
                                  scenario + annee ~ usage)

comp_conso_ref=comp_conso_ref[,list(Chauffage,
                                      AU_usages_ther = sum(ECS,Cuisson,Autre),
                                      Elec_spe = sum(Auxiliaires,Ventilation,Process,Bureautique,Eclairage,Froid_alimentaire),
                                      Climatisation,
 Total_RT=sum(Chauffage,Climatisation,ECS,Auxiliaires,Ventilation,Eclairage),                                      Total=sum(Chauffage,Climatisation,ECS,Cuisson,Autre,Auxiliaires,Ventilation,Process,Bureautique,Eclairage,Froid_alimentaire) ), by=c("scenario","annee")]

comp_conso_ref = melt(comp_conso_ref,id.vars = c("scenario","annee"),variable.name ="usage" )

comp_conso_ref[, conso_mtep := value/11630*10^3]
comp_conso_ref[, conso := value]


conso_parusage_ref = comp_conso_ref[scenario ==scenario_ref] 
comp_conso_ref = comp_conso_ref[scenario !=scenario_ref]
comp_conso_ref = merge(comp_conso_ref,conso_parusage_ref[,list(conso_ref = conso,conso_mtep_ref=conso_mtep,annee,usage )], by=c("annee","usage"))
comp_conso_ref[, diffconso := (conso-conso_ref)]

tab_diffconso_2010_2020 = comp_conso_ref[annee%in% 2014:2020]
tab_diffconso_2010_2020 = dcast.data.table(tab_diffconso_2010_2020,usage+scenario~annee, value.var = "diffconso")

tab_diffconso_2010_2020 
``` 


```{r, echo=F, warning=F,}
pander(conso_parusage_tWh[order(usage)], digits = 2, caption = "Bilan des consommations en tWh EF")
```

```{r, echo=F, warning=F,}
pander(evolconso[order(usage)], digits = 2, caption = "Evolution des consommations")
```

\section{2) Parts de marchés des systèmes et des énergies de chauffage}


### PM des énergies dans le neuf

```{r,echo=F, warning=F,include = F}
### PM des énergies dans le neuf


PM_energie_neuf = PM[Type_parc ==  "N", list(Surf_neuf_n = sum(surface)),by=c("scenario", "Type_parc","energieChauffage","periodeSimple","annee")] 

PM_energie_neuf[, annee_n1 := as.factor(as.numeric(as.character(annee)) -1)]

PM_energie_neuf = merge(PM_energie_neuf,
                        PM_energie_neuf[,list(scenario,Type_parc,annee,energieChauffage,periodeSimple,Surf_neuf_n1 = Surf_neuf_n )], 
                        by.x=c("scenario", "Type_parc","energieChauffage","periodeSimple","annee_n1"), 
                        by.y=c("scenario", "Type_parc","energieChauffage","periodeSimple","annee"))


PM_energie_neuf[,surf_cons_n := Surf_neuf_n - Surf_neuf_n1]
PM_energie_neuf[, PM_ener_neuf := surf_cons_n/sum(surf_cons_n),by=c("scenario", "Type_parc","periodeSimple","annee")]

PM_energie_neuf = PM_energie_neuf[(annee %in% 2010:2015 & periodeSimple=="04")|(annee %in% 2016:2020 & periodeSimple=="05")|
                                    (annee %in% 2021:2030 & periodeSimple=="06")|(annee %in% 2031:2040 & periodeSimple=="07")|(annee %in% 2041:2050 & periodeSimple=="08")] 
PM_energie_neuf[,sum(PM_ener_neuf), by="annee"]

PM_energie_neuf = merge(PM_energie_neuf,COD_ENERGIE[, list(energieChauffage =  COD_ENERGIE, Energie = ENERGIE)], by="energieChauffage")

dcast(PM_energie_neuf, scenario+Energie~ annee, value.var ="PM_ener_neuf")
### PM dans le parc construit après 2010
PM_energie_neuf_DGEC =parc_melted[Type_parc ==  "N", list(Surf_neuf_n = sum(Surface)),by=c("scenario", "Type_parc","energieChauffage","annee")] 
PM_energie_neuf_DGEC[, PM_ener_neuf := Surf_neuf_n/sum(Surf_neuf_n ),by=c("scenario", "Type_parc","annee")]
PM_energie_neuf_DGEC = merge(PM_energie_neuf_DGEC,COD_ENERGIE[, list(energieChauffage =  COD_ENERGIE, Energie = ENERGIE)], by="energieChauffage")


## PM systeme neuf 


PM_syst_neuf = PM[Type_parc ==  "N", list(Surf_neuf_n = sum(surface)),by=c("scenario", "Type_parc","systeme_chauff","periodeSimple","annee")] 

PM_syst_neuf [, annee_n1 := as.factor(as.numeric(as.character(annee)) -1)]

PM_syst_neuf = merge(PM_syst_neuf ,
                        PM_syst_neuf [,list(scenario,Type_parc,annee,systeme_chauff,periodeSimple,Surf_neuf_n1 = Surf_neuf_n )], 
                        by.x=c("scenario", "Type_parc","systeme_chauff","periodeSimple","annee_n1"), 
                        by.y=c("scenario", "Type_parc","systeme_chauff","periodeSimple","annee"))


PM_syst_neuf[,surf_cons_n := Surf_neuf_n - Surf_neuf_n1]
PM_syst_neuf[, PM_syst_neuf := surf_cons_n/sum(surf_cons_n),by=c("scenario", "Type_parc","periodeSimple","annee")]

PM_syst_neuf = PM_syst_neuf[(annee %in% 2010:2015 & periodeSimple=="04")|(annee %in% 2016:2020 & periodeSimple=="05")|
                                    (annee %in% 2021:2030 & periodeSimple=="06")|(annee %in% 2031:2040 & periodeSimple=="07")|(annee %in% 2041:2050 & periodeSimple=="08")] 
PM_syst_neuf[,sum(PM_syst_neuf), by="annee"]

PM_syst_neuf = merge(PM_syst_neuf,COD_SYSTEME_CHAUD[, list(systeme_chauff =  COD_SYSTEME_CHAUD, SYSTEME_CHAUD= SYSTEME_CHAUD)], by="systeme_chauff")

PM_syst_neuf[,SYSTEME_CHAUD := factor(SYSTEME_CHAUD, levels = c("Chaudière gaz","Chaudière condensation gaz",
                                                           "Tube radiant", "Tube radiant performant" ,
                                                           "Chaudière fioul","Chaudière condensation fioul",
                                                           "Electrique direct","Electrique direct performant",
                                                           "Cassette rayonnante","Cassette rayonnante performant",
                                                           "PAC","PAC performant",
                                                           "Rooftop", "Rooftop performant",
                                                            "DRV", "DRV performant",
                                                           "Autre système centralisé",  
                                                           "Autre système centralisé performant",
                                                           "nr"))]
unique(PM_syst_neuf$SYSTEME_CHAUD)

PM_syst_neuf= merge(PM_syst_neuf,colors_syst, by="SYSTEME_CHAUD")



```

\newpage 

```{r Evol_PM_energie_neuf, fig.width=25, fig.height=9, echo=F, warning=F,fig.cap='Part des surfaces neuves construites par énergie (input DGEC)', dev=c('png', 'pdf')}

ggplot(PM_energie_neuf) +
           geom_bar(aes(annee,PM_ener_neuf , fill = Energie, color = Energie), stat="identity") +
           facet_wrap(~scenario, nrow = 1) +
           mytheme_facet_plot  +
    scale_x_discrete(breaks = seq(2010,2050,5), labels =
                    seq(2010,2050,5)) 
```

```{r Evol_PM_syst_neuf, fig.width=25, fig.height=13, echo=F, warning=F,fig.cap='Part des surfaces neuves construites par système', dev=c('png', 'pdf')}

ggplot(PM_syst_neuf) +
           geom_bar(aes(annee,PM_syst_neuf , fill = SYSTEME_CHAUD, color = SYSTEME_CHAUD), stat="identity") +
           facet_wrap(~scenario, nrow = 1) +
           mytheme_facet_plot  +
    scale_x_discrete(breaks = seq(2010,2050,5), labels =
                    seq(2010,2050,5))  +
     theme(legend.position = "top") +
  scale_fill_manual(values=unique(PM_syst_neuf$color),
                    guide = guide_legend(nrow = 4)) 
```

## Changements de système dans l'existant

```{r,echo=F, warning=F,include = F}


PM_syst_br = COUTS[!is.na(COD_SYSTEME_CHAUD), list(surface = sum(surface)), by=c("scenario","annee","SYSTEME_CHAUD","COD_SYSTEME_CHAUD", "branche")]
PM_syst_br [,PM_syst := surface/sum(surface) , by=c("scenario","annee", "branche")]
PM_syst_br = merge(PM_syst_br ,COD_BRANCHE[,list(branche=COD_BRANCHE,BRANCHE)],by="branche")

PM_syst_Etat = COUTS[!is.na(COD_SYSTEME_CHAUD) & occupant=="03", list(surface = sum(surface)), by=c("scenario","annee","SYSTEME_CHAUD","COD_SYSTEME_CHAUD")]
COUTS[COD_SYSTEME_CHAUD %in% c("05","06","09","10","11","25","26","29","30","31") & annee == "2010", sum(surface)]

COUTS[COD_SYSTEME_CHAUD %in% c("05"), typeRenovationSysteme]

PM_syst = COUTS[!is.na(COD_SYSTEME_CHAUD), list(surface = sum(surface)), by=c("scenario","annee","SYSTEME_CHAUD","COD_SYSTEME_CHAUD")]


PM_syst[,PM_syst := surface/sum(surface) , by=c("scenario","annee")]
PM_syst[, sum(surface),by="annee"]
PM_syst[COD_SYSTEME_CHAUD == "24"]

PM_syst[,SYSTEME_CHAUD := factor(SYSTEME_CHAUD, levels = c("Chaudière gaz","Chaudière condensation gaz",
                                                           "Tube radiant", "Tube radiant performant" ,
                                                           "Chaudière fioul","Chaudière condensation fioul",
                                                           "Electrique direct","Electrique direct performant",
                                                           "Cassette rayonnante","Cassette rayonnante performant",
                                                           "PAC","PAC performant",
                                                           "Rooftop", "Rooftop performant",
                                                            "DRV", "DRV performant",
                                                           "Autre système centralisé",  
                                                           "Autre système centralisé performant",
                                                           "nr"))]
unique(PM_syst$SYSTEME_CHAUD)

PM_syst= merge(PM_syst,colors_syst, by="SYSTEME_CHAUD")




PM_syst_br[,SYSTEME_CHAUD := factor(SYSTEME_CHAUD, levels = c("Chaudière gaz","Chaudière condensation gaz",
                                                           "Tube radiant", "Tube radiant performant" ,
                                                           "Chaudière fioul","Chaudière condensation fioul",
                                                           "Electrique direct","Electrique direct performant",
                                                           "Cassette rayonnante","Cassette rayonnante performant",
                                                           "PAC","PAC performant",
                                                           "Rooftop", "Rooftop performant",
                                                            "DRV", "DRV performant",
                                                           "Autre système centralisé",  
                                                           "Autre système centralisé performant",
                                                           "nr"))]
unique(PM_syst_br$SYSTEME_CHAUD)

PM_syst_br= merge(PM_syst_br,colors_syst, by="SYSTEME_CHAUD")

PM_syst_Etat [,PM_syst := surface/sum(surface) , by=c("scenario","annee")]
PM_syst_Etat [, sum(surface),by="annee"]
PM_syst_Etat [COD_SYSTEME_CHAUD == "24"]

PM_syst_Etat[PM_syst <0]


levels(PM_syst$SYSTEME_CHAUD)


```

```{r Evol_PM_syst, fig.width=25, fig.height=13, echo=F, warning=F,fig.cap='Part des changements de système existant par système installé', dev=c('png', 'pdf')}

ggplot(PM_syst) +
           geom_bar(aes(annee,PM_syst , fill = SYSTEME_CHAUD), stat="identity") +
           facet_wrap(~scenario, nrow = 1) +
           mytheme_facet_plot+ theme(legend.position = "top")+
  
  scale_fill_manual(values=unique(PM_syst$color),
                    guide = guide_legend(nrow = 4)) 



```

```{r Evol_PM_syst_ref, fig.width=25, fig.height=13, echo=F, warning=F,fig.cap='Part des changements de système existant par système installé', dev=c('png', 'pdf')}

ggplot(PM_syst[scenario == scenario_ref]) +
           geom_bar(aes(annee,PM_syst , fill = SYSTEME_CHAUD), stat="identity") +
           facet_wrap(~scenario, nrow = 1) +
           mytheme_facet_plot+ theme(legend.position = "top")+
  
  scale_fill_manual(values=unique(PM_syst[scenario == scenario_ref]$color),
                    guide = guide_legend(nrow = 4)) 

```


```{r,echo=F, warning=F,include = F}
### PM des systèmes dans sur l'ensemble du parc
PM_syst_exi = etiquette[, list(Surf_exi_n = sum(surface)),by=c("scenario","annee","systeme_chauff")] 
PM_syst_exi2 = PM[, list(Surf_exi_n = sum(surface)),by=c("scenario","annee","systeme_chauff")] 

PM_syst_exi[,PM_syst_exi := Surf_exi_n /sum(Surf_exi_n ),by=c("scenario","annee")]
PM_syst_exi2[,PM_syst_exi := Surf_exi_n /sum(Surf_exi_n ),by=c("scenario","annee")]

PM_syst_exi[,sum(PM_syst_exi), by=c("scenario","annee")]
PM_syst_exi2[,sum(PM_syst_exi), by=c("scenario","annee")]

PM_syst_exi = merge(PM_syst_exi,COD_SYSTEME_CHAUD[, list(systeme_chauff =  COD_SYSTEME_CHAUD, SYSTEME_CHAUD)], by="systeme_chauff")
PM_syst_exi2 = merge(PM_syst_exi2,COD_SYSTEME_CHAUD[, list(systeme_chauff =  COD_SYSTEME_CHAUD, SYSTEME_CHAUD)], by="systeme_chauff")

PM_syst_exi = rbind(PM_syst_exi,PM_syst_exi2 )
PM_syst_exi[,SYSTEME_CHAUD := factor(SYSTEME_CHAUD, levels = c("Chaudière gaz","Chaudière condensation gaz",
                                                           "Tube radiant", "Tube radiant performant" ,
                                                           "Chaudière fioul","Chaudière condensation fioul",
                                                           "Electrique direct","Electrique direct performant",
                                                           "Cassette rayonnante","Cassette rayonnante performant",
                                                           "PAC","PAC performant",
                                                           "Rooftop", "Rooftop performant",
                                                            "DRV", "DRV performant",
                                                           "Autre système centralisé",  
                                                           "Autre système centralisé performant",
                                                           "nr"))]


PM_syst_exi = dcast.data.table(PM_syst_exi[annee %in% seq(2010,2050,5)],scenario +SYSTEME_CHAUD~annee,value.var ="PM_syst_exi")

PM_syst_exi = merge(PM_syst_exi,colors_syst, by="SYSTEME_CHAUD")



```

<!-- ```{r, echo=F, warning=F} -->
<!-- pander(PM_syst_exi, digits = 2, caption = "Part des surfaces chauffées de l'ensemble du parc  par système (input DGEC)") -->
<!-- ``` -->

```{r Evol_PM_syst_all, fig.width=25, fig.height=13, echo=F, warning=F,fig.cap='Part des systèmes sur l\'ensemble du parc', dev=c('png', 'pdf')}

ggplot(melt(PM_syst_exi,id.vars = c("scenario","SYSTEME_CHAUD","color"),variable.name = "annee",value.name = "PM_syst")) +
           geom_bar(aes(annee,PM_syst , fill = SYSTEME_CHAUD, color = SYSTEME_CHAUD), stat="identity") +
           facet_wrap(~scenario, nrow = 1) +
           mytheme_facet_plot + theme(legend.position = "top")+
  
  scale_fill_manual(values=unique(PM_syst_exi$color),
                    guide = guide_legend(nrow = 4)) 

```

\section{3) Nombre de Rénovations et Investissements }

## part du parc rénovés
```{r,  echo=F, warning=F,include = F}

cout_geste = fread("table_param_origine/Bibli_geste_bati.csv", 
                   colClasses = list("character" = c("ID_AGREG","EXIGENCE","GESTE")))

cout_geste[, COD_BRANCHE:=substring(ID_AGREG, 1,2)]
cout_geste[, COD_SS_BRANCHE:=substring(ID_AGREG, 3,4)]
cout_geste[, COD_BAT_TYPE:=substring(ID_AGREG, 5,6)]
cout_geste[, COD_PERIODE_DETAIL :=substring(ID_AGREG, 7,8)]
cout_geste[, COD_PERIODE_SIMPLE:=substring(ID_AGREG, 9,10)]

cout_geste = merge(cout_geste, COD_BRANCHE, by="COD_BRANCHE") 
cout_geste = merge(cout_geste, COD_SS_BRANCHE, by="COD_SS_BRANCHE") 
cout_geste = merge(cout_geste, COD_BAT_TYPE, by="COD_BAT_TYPE") 
cout_geste = merge(cout_geste, COD_PERIODE_DETAIL, by="COD_PERIODE_DETAIL", all.x = T) 
cout_geste = merge(cout_geste, COD_PERIODE_SIMPLE, by="COD_PERIODE_SIMPLE") 

setkeyv(cout_geste,c("BRANCHE","SS_BRANCHE", "BAT_TYPE"))
ordre = unique(cout_geste$SS_BRANCHE)
cout_geste[, SS_BRANCHE:=factor(SS_BRANCHE, levels = ordre )]
cout_geste[, PERIODE_SIMPLE:=factor(PERIODE_SIMPLE)]
cout_geste[, PERIODE_SIMPLE:=relevel(PERIODE_SIMPLE, ref = "Av 1980")]

cout_geste[GAIN!=0,mean(GAIN,na.rm=T), by="GESTE"]
cout_geste[,quantile(GAIN), by="GESTE"]

### 

Corresp_geste = data.table(GESTE = unique(cout_geste$GESTE))
Corresp_geste[GESTE %in% c("FENMOD","FENBBC","FEN_MURMOD","GTB"), GESTE_DGEC:="Rénovation faible"]
Corresp_geste[GESTE %in% c("FEN_MURBBC","ENSMOD"), GESTE_DGEC:="Rénovation moyenne"]
Corresp_geste[GESTE %in% c("ENSBBC"), GESTE_DGEC:="Rénovation importante"]


cout_geste = merge(cout_geste,Corresp_geste, by="GESTE")
cout_geste[GAIN!=0,mean(GAIN,na.rm=T), by="GESTE_DGEC"]


### calcul surfaces parc rénovés 

PM_geste_natio = COUTS[ typeRenovationBatiment !="Etat initial",]
PM_geste_natio = merge(PM_geste_natio,Corresp_geste, by.x="typeRenovationBatiment",by.y="GESTE")
PM_geste_natio[, annee := as.factor(annee)]
PM_geste_natio[,  GESTE_DGEC := factor(GESTE_DGEC, levels = c("Parc non touché","Rénovation faible","Dont GTB","Rénovation moyenne","Rénovation importante"))]

Surface_parc_Renov = PM_geste_natio[ typeRenovationBatiment !="Etat initial",list(Surface_Renov = sum(surface)),by=c("scenario","annee")]

Surface_parc_exi = parc_melted[, list(Surface_parc_exi = sum(Surface)),by=c("scenario","annee")]
Surface_parc_exi[, annee := as.factor(annee)]

Surface_parc_Renov = merge(Surface_parc_Renov ,Surface_parc_exi,by=c("scenario","annee"))
Surface_parc_Renov[, PM_Geste := 1-Surface_Renov/Surface_parc_exi,by=c("scenario","annee")]
Surface_parc_Renov[, "GESTE_DGEC" := "Parc non touché",]

Surface_parc_GTB = PM_geste_natio[ typeRenovationBatiment =="GTB",list(Surface_Renov = sum(surface)),by=c("scenario","annee")]
Surface_parc_GTB = merge(Surface_parc_GTB ,Surface_parc_exi,by=c("scenario","annee"))
Surface_parc_GTB[, PM_Geste := Surface_Renov/Surface_parc_exi,by=c("scenario","annee")]
Surface_parc_GTB[, "GESTE_DGEC" := "Dont GTB",]


PM_geste_natio = PM_geste_natio[ typeRenovationBatiment !="Etat initial", list(Surface_Renov = sum(surface)),by=c("scenario","annee","GESTE_DGEC")]

PM_geste_natio[,Surface_tot_Renov := sum(Surface_Renov ),by=c("scenario","annee")]
PM_geste_natio = merge(PM_geste_natio,Surface_parc_exi,by=c("scenario","annee")  )

PM_geste_natio[,PM_Geste := Surface_Renov/Surface_parc_exi]

tab_PM_geste = dcast.data.table(PM_geste_natio[annee %in% seq(2010,2050,5)], scenario+GESTE_DGEC~annee,value.var = "PM_Geste")
tab_PM_Non_Renov = dcast.data.table(Surface_parc_Renov[annee %in% seq(2010,2050,5)], scenario+GESTE_DGEC~annee,value.var = "PM_Geste")
tab_PM_Non_GTB = dcast.data.table(Surface_parc_GTB[annee %in% seq(2010,2050,5)], scenario+GESTE_DGEC~annee,value.var = "PM_Geste")
tab_PM_geste = rbindlist(list(tab_PM_Non_Renov,tab_PM_geste,tab_PM_Non_GTB) )
tab_PM_geste = replace(tab_PM_geste,is.na(tab_PM_geste),0)

tab_PM_geste[,  GESTE_DGEC := factor(GESTE_DGEC, levels = c("Parc non touché","Rénovation faible","Dont GTB","Rénovation moyenne","Rénovation importante"))]
tab_PM_geste = tab_PM_geste[order(GESTE_DGEC)]

## Cumul du parc rénové 
PM_geste_natio = PM_geste_natio[order(annee)]
PM_geste_natio_cum  = PM_geste_natio[, list(annee,Surface_tot_Renov,Surface_parc_exi,Surface_Renov_cum = cumsum(Surface_Renov)), by=c("scenario","GESTE_DGEC")]
PM_geste_natio_cum[, PM_Geste := Surface_Renov_cum/Surface_parc_exi]

tab_PM_geste_cum = dcast.data.table(PM_geste_natio_cum[annee %in% seq(2010,2050,5)], scenario+GESTE_DGEC~annee,value.var = "PM_Geste")

## PArc de l'Etat rénové
Surface_parc_Renov_Etat = COUTS[occupant == "03" & typeRenovationBatiment !="Etat initial",list(Surface_Renov = sum(surface)),by=c("scenario","annee")]

Surface_parc_Renov_Etat_Regl = COUTS[occupant == "03" & typeRenovationBatiment !="Etat initial"& reglementation=="ObligationTravaux", list(Surface_Renov_Regl = sum(surface)),by=c("scenario","annee")]

Surface_parc_Renov_Etat_perf =COUTS[occupant == "03" & typeRenovationBatiment !="Etat initial",list(Surface_Renov = sum(surface)),by=c("scenario","annee", "typeRenovationBatiment")]

Surface_parc_Renov_Etat_perf_Regl  =COUTS[occupant == "03" & typeRenovationBatiment !="Etat initial" & reglementation=="ObligationTravaux",list(Surface_Renov = sum(surface)),by=c("scenario","annee", "typeRenovationBatiment")]


if(nrow(Surface_parc_Renov_Etat_Regl)==0){
  Surface_parc_Renov_Etat_Regl = Surface_parc_Renov_Etat
  Surface_parc_Renov_Etat_Regl[,Surface_Renov_Regl:= 0]
}

Surface_parc_Renov_Etat = dcast.data.table(Surface_parc_Renov_Etat[annee %in% seq(2010,2050,5)], scenario~annee,value.var = "Surface_Renov")


Surface_parc_Renov_Etat_Regl = dcast.data.table(Surface_parc_Renov_Etat_Regl[annee %in% seq(2010,2050,5)], scenario~annee,value.var = "Surface_Renov_Regl")

Surface_parc_Renov_Etat_perf = dcast.data.table(Surface_parc_Renov_Etat_perf[annee %in% seq(2010,2050,5)], scenario + typeRenovationBatiment~annee,value.var = "Surface_Renov")

Surface_parc_Renov_Etat_perf_Regl = dcast.data.table(Surface_parc_Renov_Etat_perf_Regl[annee %in% seq(2010,2050,5)], scenario + typeRenovationBatiment~annee,value.var = "Surface_Renov")


Surface_parc_Etat_tot = 
dcast.data.table(parc_melted[occupation=="03" & Type_parc=="E", sum(Surface),by=c("scenario","annee")],  scenario ~annee,value.var = "V1")
Surface_parc_Etat_arenov = 
dcast.data.table(parc_melted[occupation=="03" & Type_parc=="E", sum(Surface)*0.03,by=c("scenario","annee")],  scenario ~annee,value.var = "V1")

```

```{r, echo=F, warning=F,}
pander(tab_PM_geste, digits = 2, caption = "Parc du parc rénové annuellement par niveau de rénovation")
```

```{r, echo=F, warning=F,}
pander(tab_PM_geste_cum, digits = 2, caption = "Parc du parc rénové (cumul)")
```

```{r, echo=F, warning=F,}
pander(Surface_parc_Renov_Etat, digits = 2, caption = "Parc du parc de l'Etat rénové annuellement")
```

```{r, echo=F, warning=F,}
pander(Surface_parc_Renov_Etat_Regl, digits = 2, caption = "Parc du parc de l'Etat rénové annuellement du fait de la directive patrimoine immobilier de l'Etat")
```

## Surfaces rénovées 

```{r,  echo=F, warning=F,include = F}

Surfaces_renov_gestes = COUTS[typeRenovationBatiment !="Etat initial",list(surface = sum(surface)/10^6,investissement = sum(investissement)/10^6), by=c("scenario","annee","typeRenovationBatiment")]
Surfaces_renov_gestes[,Geste := factor(typeRenovationBatiment, levels = c("GTB","FENMOD","FEN_MURMOD","ENSMOD","FENBBC","FEN_MURBBC","ENSBBC"))]
Surfaces_renov_gestes = Surfaces_renov_gestes[order(Geste)]

Surfaces_renov_gestes_cum = Surfaces_renov_gestes[,list(INV_cum_geste = cumsum(investissement),INV =investissement, 
                                                        surface_cum_geste = cumsum(surface),surface=surface,
                                                         Geste), by=c("scenario","annee")]


Surfaces_renov_gestes_cum[,Geste := factor(Geste, levels = rev(c("GTB","FENMOD","FEN_MURMOD","ENSMOD","FENBBC","FEN_MURBBC","ENSBBC")))]


Surfaces_renov_syst = COUTS[typeRenovationSysteme != "Etat initial_NP",list(surface = sum(surface)/10^6,investissement = sum(investissement)/10^6), by=c("scenario","annee","typeRenovationSysteme","SYSTEME_CHAUD")]

COUTS[typeRenovationSysteme != "Etat initial_NP", unique(typeRenovationBatiment)]

Surfaces_renov_syst[,Systeme := factor(SYSTEME_CHAUD, levels = c("Chaudière gaz","Chaudière condensation gaz",
                                                           "Chaudière fioul","Chaudière condensation fioul",
                                                           "Electrique direct","Electrique direct performant",
                                                           "PAC","PAC performant",
                                                           "Rooftop", "Rooftop performant",
                                                           "Tube radiant", "Tube radiant performant" ,
                                                           "Cassette rayonnante","Cassette rayonnante performant",
                                                           "DRV", "DRV performant",
                                                           "Autre système centralisé",  "Autre système centralisé performant",
                                                           "nr"))]
Surfaces_renov_syst = Surfaces_renov_syst[order(Systeme)]

Surfaces_renov_syst_cum =Surfaces_renov_syst[,list(INV_cum_syst = cumsum(investissement),INV =investissement, 
                                                        surface_cum_syst = cumsum(surface),surface=surface,
                                                         Systeme), by=c("scenario","annee")]


Surfaces_renov_syst_cum [,Systeme := factor(Systeme, levels = rev(levels(Surfaces_renov_syst$Systeme)))]


```

```{r Surfaces_Renov, fig.width=20, fig.height=9, echo=F, warning=F, fig.show='hold', dev=c('png', 'pdf')}
  
ggplot(Surfaces_renov_gestes_cum) + 
  geom_ribbon(aes(ymin = 0, annee, ymax =  surface_cum_geste, group =Geste, fill = Geste)) +  ylab("Millions de m²") + ggtitle("Surfaces rénovées par geste") + xlab("annee") +
  mytheme_facet_plot + scale_color_brewer(palette = fillpalette) +
  scale_y_continuous(limits  = c(0,100)) + facet_wrap(~scenario)

ggplot(Surfaces_renov_syst_cum) + 
  geom_ribbon(aes(ymin = 0, annee, ymax =  surface_cum_syst , group =Systeme, fill = Systeme)) +  ylab("Millions de m²") + ggtitle("Surfaces rénovées par système de chauffage") + xlab("annee") +
  mytheme_facet_plot + scale_color_brewer(palette = fillpalette) +
  scale_y_continuous(limits  = c(0,100)) + facet_wrap(~scenario) + guides(fill=guide_legend(ncol=2))
    
```

## Investissements 
```{r,  echo=F, warning=F,include = F}
### calcul investissement annuel et cumulés

INV_AUTRES_TOT = INV_AUTRES_renov[,list(INV = sum(value)), by=c("scenario","annee")]
INV_GESTE_TOT = INV_GESTE[,list(INV = sum(value)), by=c("scenario","annee")]
INV_SYST_CHAUD_TOT = INV_SYST_CHAUD[,list(INV = sum(value)), by=c("scenario","annee")]


unique(COUTS$typeRenovationSysteme)
unique(COUTS$SYSTEME_CHAUD)

COUTS[,list(surface = sum(surface)), by=c("scenario","annee")]


INV_GESTE_TOT[,list(INV = sum(INV)/10^3), by=c("scenario")]
INV_SYST_CHAUD_TOT[,list(INV = sum(INV)/10^3), by=c("scenario")]

INV_SYST_CHAUD[,Systeme := factor(SYSTEME_CHAUD, levels = c("Chaudière gaz","Chaudière condensation gaz",
                                                           "Chaudière fioul","Chaudière condensation fioul",
                                                           "Electrique direct","Electrique direct performant",
                                                           "PAC","PAC performant",
                                                           "Rooftop", "Rooftop performant",
                                                           "Tube radiant", "Tube radiant performant" ,
                                                           "Cassette rayonnante","Cassette rayonnante performant",
                                                           "DRV", "DRV performant",
                                                           "Autre système centralisé",  "Autre système centralisé performant",
                                                           "nr"))]

INV_SYST_tab = INV_SYST_CHAUD[,list(INV = sum(value, na.rm=T)/10^3), by=c("scenario", "Systeme")]
INV_SYST_tab =INV_SYST_tab[INV >0.01]

INV_SYST_CHAUD = INV_SYST_CHAUD[order(Systeme)]

INV_SYST_cum = INV_SYST_CHAUD [,list(INV_cum_syst = cumsum(value),INV =value, Systeme), by=c("scenario","annee")]

INV_SYST_cum [,Systeme := factor(Systeme, levels = rev(levels(INV_SYST_CHAUD$Systeme)))]



INV_GESTE[,Geste := factor(variable, levels = c("GTB","FENMOD","FEN_MURMOD","ENSMOD","FENBBC","FEN_MURBBC","ENSBBC"))]

INV_GESTE_tab = INV_GESTE[,list(INV = sum(value, na.rm=T)/10^3), by=c("scenario","Geste")]

INV_GESTE = INV_GESTE[order(Geste)]
INV_GESTE_cum = INV_GESTE[,list(INV_cum_geste = cumsum(value),INV =value, Geste), by=c("scenario","annee")]

INV_GESTE_cum[,Geste := factor(Geste, levels = rev(c("GTB","FENMOD","FEN_MURMOD","ENSMOD","FENBBC","FEN_MURBBC","ENSBBC")))]


INV_AUTRES_renov[,Usages := factor(variable, levels = c("Climatisation","ECS","Eclairage"))]

INV_AUTRES_renov = INV_AUTRES_renov[order(Usages)]
INV_AUTRES_renov_cum = INV_AUTRES_renov[,list(INV_cum_autres = cumsum(value),INV =value, Usages), by=c("scenario","annee")]

INV_AUTRES_renov_cum[,Usages := factor(Usages, levels = rev(c("Climatisation","ECS","Eclairage")))]


```



```{r INV_syst, fig.width=20, fig.height=9, echo=F, warning=F, fig.show='hold', dev=c('png', 'pdf')}
ggplot(INV_SYST_tab ) +
  geom_bar(aes(substring(scenario,1,2),INV, color =Systeme,fill =Systeme), stat = "identity") +
  ylab("Mds euros") + ggtitle("Investissements cumulées dans les systèmes de chauffage") + xlab("scenario") +
  mytheme_facet_plot +  scale_x_discrete(breaks = c("2008", seq(2010,2050,10))) +
  scale_y_continuous(limits  = c(0,100)) 
# 
# ggplot( INV_SYST_CHAUD) +
#   geom_line(aes(annee,value, color =Systeme), stat = "identity", size = 2) +
#   ylab("Millions d'euros") + ggtitle("Investissements dans les systèmes de chauffage") + xlab("annee") +
#   mytheme_facet_plot +
#   scale_y_continuous(limits  = c(0,1000)) + facet_wrap(~scenario)

ggplot(INV_SYST_cum) + 
  geom_ribbon(aes(ymin = 0, annee, ymax = INV_cum_syst, group =Systeme, fill = Systeme)) + 
    ylab("Millions d'euros") + facet_wrap(~scenario) +  ggtitle("Investissements dans les systèmes de chauffage")+       xlab("annee") +
  mytheme_facet_plot
  
```

```{r INV_Gestes, fig.width=20, fig.height=9, echo=F, warning=F, fig.show='hold', dev=c('png', 'pdf')}
  
ggplot(INV_GESTE_tab ) +
  geom_bar(aes(substring(scenario,1,2),INV, color =Geste,fill =Geste), stat = "identity") +
  ylab("Mds euros") + ggtitle("Investissements cumulées dans les rénovations") + xlab("scenario") +
  mytheme_facet_plot +  scale_x_discrete(breaks = c("2008", seq(2010,2050,10))) +
  scale_y_continuous(limits  = c(0,100))
# 
# ggplot( INV_GESTE) +
#   geom_line(aes(annee,value, color =Geste), stat = "identity", size = 2) +
#   ylab("Millions d'euros") + ggtitle("Investissements dans les rénovations") + xlab("annee") +
#   mytheme_facet_plot + scale_color_brewer(palette = fillpalette) +
#   scale_y_continuous(limits  = c(0,2000)) + facet_wrap(~scenario)

ggplot(INV_GESTE_cum) + 
  geom_ribbon(aes(ymin = 0, annee, ymax = INV_cum_geste, group =Geste, fill = Geste)) + 
    ylab("Millions d'euros") + ggtitle("Investissements dans les rénovations") + facet_wrap(~scenario) +
  mytheme_facet_plot + scale_fill_brewer(palette = fillpalette) 
  
```

```{r INV_Autres, fig.width=20, fig.height=9, echo=F, warning=F, fig.show='hold', dev=c('png', 'pdf')}
  
# ggplot(INV_AUTRES_renov) +
#   geom_line(aes(annee,value, color =Usages), stat = "identity", size = 2) +
#   ylab("Millions d'euros") + ggtitle("Investissements dans les autres usages RT") + xlab("annee") +
#   mytheme_facet_plot + scale_color_brewer(palette = fillpalette) +
#   scale_y_continuous(limits  = c(0,4000)) + facet_wrap(~scenario)

ggplot(INV_AUTRES_renov_cum) + 
  geom_ribbon(aes(ymin = 0, annee, ymax =  INV_cum_autres, group =Usages, fill = Usages)) + 
    ylab("Millions d'euros") + ggtitle("Investissements dans les autres usages RT") + facet_wrap(~scenario) +
  mytheme_facet_plot + scale_fill_brewer(palette = fillpalette) 


```

```{r,  echo=F, warning=F,include = F}


####### Investissements par type de rénovation 
INV_SYST_CHAUD = dcast.data.table(COUTS, scenario +annee ~ typeRenovationSysteme, value.var = "investissement", 
                                  fun.aggregate = function(x){sum(x)/10^6})
INV_SYST_CHAUD[,"Etat initial_NP" := NULL]
INV_SYST_CHAUD = melt(INV_SYST_CHAUD,id.vars = c("scenario","annee"))
INV_SYST_CHAUD[, COD_SYSTEME_CHAUD := substring(variable,14,16)]
INV_SYST_CHAUD = merge(INV_SYST_CHAUD, COD_SYSTEME_CHAUD, by="COD_SYSTEME_CHAUD")

INV_GESTE = dcast.data.table(COUTS, scenario + annee ~ typeRenovationBatiment, value.var = "investissement", 
                             fun.aggregate = function(x){sum(x)/10^6})

INV_GESTE[,"Etat initial":=NULL]
INV_GESTE = melt(INV_GESTE,id.vars = c("scenario","annee"))

INV_AUTRES_renov = dcast.data.table(COUTS_AUTRES, scenario + annee ~ typeRenovationSysteme, value.var = "investissement", 
                                    fun.aggregate = function(x){sum(x)/10^6})

INV_AUTRES_renov =  melt(INV_AUTRES_renov,id.vars = c("scenario","annee"))

##### investissements au m2
COUTS[, INV_m2 := investissement/surface]
summary(COUTS)

INV_SYST_CHAUD_m2 = COUTS[, list( investissement = sum(investissement),
                                  surface = sum(surface)), by=c("scenario","annee","SYSTEME_CHAUD")]
INV_SYST_CHAUD_m2[, INV_m2 := investissement/surface]

INV_SYST_CHAUD_m2[scenario == scenario_ref ,sum(surface)/10^6,by="annee"]


ggplot(INV_SYST_CHAUD_m2[!is.na(SYSTEME_CHAUD)] ) + geom_line(aes(annee, INV_m2, group = scenario, color = scenario)) + 
  geom_point(aes(annee, INV_m2, color = scenario))+ theme(axis.text.x = element_text(angle = 45, size = 12))+
  facet_wrap(~SYSTEME_CHAUD) + 
  mytheme_facet_plot

COUTS_AUTRES[, INV_m2 := investissement/surface]
summary(COUTS_AUTRES[typeRenovationSysteme == "Climatisation"])

INV_AUTRES_renov_m2 = COUTS_AUTRES[, list( investissement = sum(investissement),
                                           surface = sum(surface)), by=c("scenario","annee","typeRenovationSysteme")]
INV_AUTRES_renov_m2[, INV_m2 := investissement/surface]

##### investissments totaux 

COUTS_all = rbind(COUTS[,list(INV_tot = sum(investissement),surface= sum(surface),aides = sum(aides),
                              prets = sum(prets),pretsBonifies = sum(pretsBonifies)),
                        by=c("scenario","annee","branche","occupant","reglementation")],
                  COUTS_AUTRES[,list(INV_tot = sum(investissement),surface= sum(surface),aides = sum(aides),
                                     prets = sum(prets),pretsBonifies = sum(pretsBonifies)),
                               by=c("scenario","annee","branche","occupant","reglementation")])
COUTS_all = rbind(COUTS[,list(INV_tot = sum(investissement),surface= sum(surface),aides = sum(aides),
                              prets = sum(prets),pretsBonifies = sum(pretsBonifies)),
                        by=c("scenario","annee","branche","occupant","reglementation")],
                  COUTS_AUTRES[,list(INV_tot = sum(investissement),surface= sum(surface),aides = sum(aides),
                                     prets = sum(prets),pretsBonifies = sum(pretsBonifies)),
                               by=c("scenario","annee","branche","occupant","reglementation")])

####### Investissements par politique/canal/aidés ou non

INV_Reglementation = COUTS_all[,list(INV_tot = sum(INV_tot),surface= sum(surface),aides = sum(aides)), by=c("scenario","annee", "reglementation")]


INV_Reglementation[,reglementation := factor(reglementation, levels = c("non","Décret", "ObligationTravaux"))]

INV_Reglementation_cum = INV_Reglementation[order(reglementation)]

INV_Reglementation_cum = INV_Reglementation[,list(INV_cum = cumsum(INV_tot),INV_tot, reglementation), by=c("scenario","annee")]
INV_Reglementation_cum[,reglementation := factor(reglementation, levels = rev(c("non","Décret", "ObligationTravaux")))]

INV_Reglementation[,sum(INV_tot),by="reglementation"]
INV_Reglementation[,sum(surface),by="reglementation"]

#### investissements au m²

INV_Reglementation[,INV_m2 := INV_tot/surface]

#### investissements aidés

INV_aides = COUTS_all[,list(INV_tot = sum(INV_tot),surface= sum(surface),aides = sum(aides), prets = sum(prets),pretsBonifies = sum(pretsBonifies)), by=c("scenario","annee","branche","occupant","reglementation")]

INV_aides = INV_aides[aides>0]

INV_aides[,unique(annee)]

INV_aides[,sum(aides)/10^6]


INV_aides_cum = COUTS_all[,list(aides = sum(aides), prets = sum(prets),
                                pretsBonifies = sum(pretsBonifies)), by=c("scenario","annee")]

INV_aides_cum = melt(INV_aides_cum, id.vars = c("scenario","annee"))

INV_aides_cum[,Type_Fin := factor(variable, levels = c("prets","aides","pretsBonifies"))]

INV_aides_cum = INV_aides_cum[order(Type_Fin)]

INV_aides_cum = INV_aides_cum[,list(INV_cum = cumsum(value),INV_tot = value, Type_Fin), by=c("scenario","annee")]
INV_aides_cum[, Type_Fin := factor(Type_Fin, levels = rev(c("prets","aides","pretsBonifies")))]


INV_aides_regl_cum = COUTS[,list(aides = sum(aides), prets = sum(prets),pretsBonifies = sum(pretsBonifies)), by=c("scenario","annee","reglementation")]

INV_aides_regl_cum = melt(INV_aides_regl_cum, id.vars = c("scenario","annee","reglementation"))

INV_aides_regl_cum[,Type_Fin := factor(variable, levels = c("prets","aides","pretsBonifies"))]

INV_aides_regl_cum  = INV_aides_regl_cum [order(Type_Fin)]

INV_aides_regl_cum = INV_aides_regl_cum[,list(INV_cum = cumsum(value),INV_tot = value, Type_Fin), by=c("scenario","annee","reglementation")]
INV_aides_regl_cum[, Type_Fin := factor(Type_Fin, levels = rev(c("prets","aides","pretsBonifies")))]

### investissements DGEC

Tab_inv_DGEC = COUTS[,list(INV = sum(investissement), surface= sum(surface)) , by=c("scenario","annee","typeRenovationBatiment","typeRenovationSysteme")]

Tab_inv_DGEC[typeRenovationBatiment =="Etat initial" & typeRenovationSysteme != "Etat initial_NP",Type_Inv :="Changement de système seul"]
Tab_inv_DGEC[typeRenovationBatiment !="Etat initial" & typeRenovationSysteme == "Etat initial_NP",Type_Inv :="Geste sur le bâti"]
Tab_inv_DGEC[typeRenovationBatiment !="Etat initial" & typeRenovationSysteme != "Etat initial_NP",Type_Inv :="Geste sur le bâti et Changement de système"]


Tab_inv_DGEC = Tab_inv_DGEC[,list(INV_Md = sum(INV)/10^9, surface= sum(surface)) , by=c("scenario","annee","Type_Inv")]

Tab_inv_DGEC = dcast.data.table(Tab_inv_DGEC[annee %in% seq(2010,2050,5)],scenario + Type_Inv~annee,value.var ="INV_Md")

```

```{r INV_reglementation, fig.width=20, fig.height=9, echo=F, warning=F, fig.show='hold', dev=c('png', 'pdf')}

ggplot(INV_Reglementation_cum) + 
  geom_ribbon(aes(ymin = 0, annee, ymax = INV_cum/10^6, group =reglementation, fill = reglementation)) + 
    ylab("Millions d'euros") + facet_wrap(~scenario) +  ggtitle("Investissements par réglementation")+       xlab("annee") +
  mytheme_facet_plot

```

```{r INV_aides, fig.width=20, fig.height=9, echo=F, warning=F, fig.show='hold', dev=c('png', 'pdf')}

ggplot(INV_aides_cum) + 
  geom_ribbon(aes(ymin = 0, annee, ymax = INV_cum/10^6, group =Type_Fin, fill = Type_Fin)) + 
  ylab("Millions d'euros") + facet_wrap(~scenario) + 
  ggtitle("Investissements et type de financement")+       xlab("annee") +
  mytheme_facet_plot

```

```{r INV_aides_regl, fig.width=20, fig.height=9, echo=F, warning=F, fig.show='hold', dev=c('png', 'pdf')}

ggplot(INV_aides_regl_cum) + 
  geom_ribbon(aes(ymin = 0, annee, ymax = INV_cum/10^6, group =Type_Fin, fill = Type_Fin)) + 
  ylab("Millions d'euros") + facet_wrap(~scenario + reglementation) + 
  ggtitle("Investissements et type de financement par réglementation")+       xlab("annee") +
  mytheme_facet_plot

```
