package com.ed.cgdd.derby.model.parc;

public enum SsBranche {
	ADMINISTRATION("01"), BUREAUX("02"), CABINET_MEDICAL("03"), CAFE_CANTINE_TRAITEUR("04"), CENTRE_ACCUEIL("05"), COMMERCE_DE_DETAIL_NON_ALIMENTAIRE(
			"06"), COMMERCE_DE_GROS("07"), CULTURE("08"), ENSEIGNEMENT_PRIMAIRE("09"), ENSEIGNEMENT_SECONDAIRE("10"), ENSEIGNEMENT_SUPERIEUR_ET_RECHERCHE(
			"11"), ENTREPOT("12"), EQUIPEMENT_COLLECTIF("13"), FOYER("14"), GARDERIE("15"), GRAND_COMMERCE_ALIMENTAIRE(
			"16"), HOPITAL("17"), HOTEL_AVEC_RESTAURANT("18"), HOTEL_SANS_RESTAURANT("19"), LOISIR("20"), MAISON_DE_PRERETRAITE(
			"21"), MAISON_RETRAITE_MEDICALISEE("22"), PETIT_COMMERCE_ALIMENTAIRE("23"), PROCESS("24"), RESIDENCE_UNIVERSITAIRE(
			"25"), RESTAURANT("26"), SERVICE("27"), SERVICE_A_LA_PERSONNE("28"), SPORT("29"), TRANSPORT_AERIEN("30"), TRANSPORT_AUTRE(
			"31"), TRANSPORT_FERROVIAIRE("32"), TRANSPORT_MARITIME_ET_FLUVIAL("33"), TRANSPORT_ROUTIER("34"), TRANSPORT_URBAIN(
			"35");

	private String code;

	private SsBranche(String code) {
		this.code = code;
	}

	public String getCode() {
		return code;
	}

	public void setCode(String code) {
		this.code = code;
	}

}
